README.md, named-entity-recognition/buildproto.sh, sentiment-analysis/buildproto.sh
Changing readme service links
Changing python version
=> Readme links

named-entity-recognition/README.md
=> Changing NER method name

named-entity-recognition/Dockerfile, named-entity-recognition/run_service.py, sentiment-analysis/Dockerfile, sentiment-analysis/requirements.txt, sentiment-analysis/run_service.py
- Daemon compile improvements
- Adding missing dependence
@andre-senna
=> Daemon compile improvements

named-entity-recognition/Dockerfile, sentiment-analysis/Dockerfile
Using last official release of the daemon
=> Using last official release of the daemon

named-entity-recognition/Dockerfile, named-entity-recognition/config/snetd_named_entity_recognition_server_config.json, named-entity-recognition/service_metadata.json, sentiment-analysis/Dockerfile, sentiment-analysis/README.md, sentiment-analysis/config/snetd_sentiment_analysis_server_config.json, sentiment-analysis/service_metadata.json
Updating sentiment analysis and named entity recognition services to use the new registry.
=> Updating to the new registry

named-entity-recognition/config/snetd_named_entity_recognition_server_config.json, sentiment-analysis/config/snetd_sentiment_analysis_server_config.json
=> Fixing daemon config

cntk-language-understanding/Dockerfile
=> [language-understanding] Dockerfile fix

.circleci/config.yml, cntk-language-understanding/service/language_understanding_service.py, docs/index.html, docs/users_guide/cntk-language-understanding.md, docs/users_guide/opennmt-romance-translator.html, docs/users_guide/opennmt-romance-translator.md, opennmt-romance-translator/Dockerfile, opennmt-romance-translator/README.md, opennmt-romance-translator/buildproto.sh, opennmt-romance-translator/requirements.txt, opennmt-romance-translator/run_romance_translator_service.py, opennmt-romance-translator/service/__init__.py, opennmt-romance-translator/service/common.py, opennmt-romance-translator/service/romance_translator.py, opennmt-romance-translator/service/romance_translator_service.py, opennmt-romance-translator/service/service_spec/romance_translator.proto, opennmt-romance-translator/test_romance_translator_service.py, opennmt-romance-translator/utils/prepare_data.sh, opennmt-romance-translator/utils/translator.sh
- Add `opennmt-romance-translator`.
=> [opennmt-romance] Add service

README.md, docs/users_guide/opennmt-romance-translator.md
- Add `opennmt-romance-translator` to the main `README.md`.
- Fix `opennmt-romance-translator` inputs URL at User's Guide.
=> [opennmt-romance] Fix READMEs

text-summarization/Dockerfile, text-summarization/buildproto.sh, translation/Dockerfile, translation/buildproto.sh
=> Build protobuf in Dockerfile

.circleci/config.yml
Fixing environment variable checks
=> Fixing environment variable checks

.circleci/config.yml
=> Fixing environment check

.circleci/config.yml
=> Updating circleci config

.circleci/config.yml
=> Improving CircleCI config

.circleci/config.yml
Adding individual service's host config
=> Adding service host configs

.circleci/config.yml
Adding docker volumes generic user path
=> Adding docker volumes generic user path

.circleci/config.yml, text-summarization/snetd.testnet.config.json, translation/snetd.testnet.config.json
=> Minor fixes

named-entity-recognition/Dockerfile, sentiment-analysis/Dockerfile, text-summarization/Dockerfile, translation/Dockerfile
=> Adding daemon v0.1.8 support

named-entity-recognition/services/service_spec/named_entity_recognition_rpc.proto
=> Removing outdated code.

.circleci/config.yml, text-summarization/run_service.py, translation/run_service.py
- Remove infinite Daemon restarting loop on `translation` and `text-summarization`.
- Add conditional steps to build jobs.
=> Remove possible infinite loop on starting Daemon.

.circleci/config.yml, named-entity-recognition/Dockerfile, named-entity-recognition/config/snetd.mainnet.config.json, named-entity-recognition/config/snetd.testnet.config.json, named-entity-recognition/requirements.txt, sentiment-analysis/Dockerfile, sentiment-analysis/config/snetd.mainnet.config.json, sentiment-analysis/config/snetd.testnet.config.json, sentiment-analysis/requirements.txt
- Updating dependencies
- Updating daemon version
- Adding new daemon config features
=> Service improvements (NER and Sentiment Analysis)

.circleci/config.yml
=> [ci] Running buildproto before service.

cntk-language-understanding/Dockerfile, named-entity-recognition/Dockerfile, sentiment-analysis/Dockerfile, text-summarization/Dockerfile, translation/Dockerfile
Sometimes the number of requests to the Github API reaches the maximum allowed and this makes the Dockefile crashes due to the Daemon's version tag, that comes from the API.
=> Adding snetd_version as Dockerfile ARG.

.circleci/config.yml, cntk-language-understanding/Dockerfile, cntk-language-understanding/config/snetd.mainnet.json, cntk-language-understanding/config/snetd.ropsten, cntk-language-understanding/service/__init__.py, named-entity-recognition/Dockerfile, opennmt-romance-translator/Dockerfile, opennmt-romance-translator/service/__init__.py, sentiment-analysis/Dockerfile, text-summarization/Dockerfile, translation/Dockerfile
- More elegant way to get Daemon's version on CI.
- Fixing gRPC port of `opennmt-romance-translator`
=> Snetd version

.circleci/check_md5.sh, .circleci/config.yml, cntk-language-understanding/Dockerfile, named-entity-recognition/Dockerfile, opennmt-romance-translator/Dockerfile, sentiment-analysis/Dockerfile, text-summarization/Dockerfile, translation/Dockerfile
Using the SingularityNET CircleCI Orb and the Daemon `v3.1.1`.
=> [repo] Using the singularitynet orb.

.circleci/config.yml
-   [ ] CircleCI tests are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md](https://dev.singularitynet.io/docs/contribute/contribution-guidelines/) document are followed
=> [ci] Fixing translation.

.circleci/config.yml
`2.2.0` -> `2.4.1`
-   [ ] CircleCI tests are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md](https://dev.singularitynet.io/docs/contribute/contribution-guidelines/) document are followed
=> Bumping Orb version

.circleci/config.yml, cntk-language-understanding/Dockerfile, cntk-language-understanding/config/snetd.mainnet.json, cntk-language-understanding/requirements.txt, cntk-language-understanding/run_service.py, named-entity-recognition/Dockerfile, named-entity-recognition/config/snetd.mainnet.json, named-entity-recognition/requirements.txt, named-entity-recognition/run_service.py, opennmt-romance-translator/Dockerfile, opennmt-romance-translator/config/snetd.mainnet.config.json, opennmt-romance-translator/requirements.txt, opennmt-romance-translator/run_service.py, sentiment-analysis/Dockerfile, sentiment-analysis/config/snetd.mainnet.json, sentiment-analysis/requirements.txt, sentiment-analysis/run_service.py, text-summarization/Dockerfile, text-summarization/config/snetd.mainnet.json, text-summarization/requirements.txt, text-summarization/run_service.py, translation/Dockerfile, translation/config/snetd.mainnet.json, translation/requirements.txt, translation/run_service.py
=>  [repo] New ports and freezing versions.

opennmt-romance-translator/requirements.txt
=> [opennmt-romance-translator] freezing setuptools and protobuf.
